### ISSUE TITLE
SPM Install fails with Invalid Secret Key format error message

### ISSUE THREAD

**Issue by sinny777** [IBM/spm-kubernetes#12]
When I try to install SPM (https://ibm.github.io/spm-kubernetes/01-deploy-spm/SPM-sw)

java -jar IBM\ Curam\ Social\ Program\ Management\ Platform\ Development.jar

I get following error message:

```
Apr 14, 2020 8:41:50 PM java.io.ObjectInputStream filterCheck
INFO: ObjectInputFilter REJECTED: class com.sun.crypto.provider.SealedObjectForKeyProtector, array length: -1, nRefs: 1, depth: 1, bytes: 70, ex: n/a
java.io.IOException: Invalid secret key format
	at com.ibm.crypto.provider.JceKeyStore.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at curam.util.security.Encryption$CryptoConfig.getKeyFromKeyStore(Encryption.java:1040)
	at curam.util.security.Encryption$CryptoConfig.getCipherKey(Encryption.java:947)
	at curam.util.security.Encryption.setConfiguration(Encryption.java:201)
	at curam.util.security.EncryptionConfiguration.<init>(EncryptionConfiguration.java:31)
	at curam.util.security.EncryptPassword.encryptDBPassword(EncryptPassword.java:16)
	at curam.installerinf.panelhelpers.BootstrapHelper.encryptPassword(BootstrapHelper.java:204)
	at curam.installerinf.panelhelpers.BootstrapHelper.updateBoostrapFile(BootstrapHelper.java:97)
	at curam.installerinf.processmanager.BootstrapManager.run(BootstrapManager.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.izforge.izpack.installer.ProcessPanelWorker$ExecutableClass.run(Unknown Source)
	at com.izforge.izpack.installer.ProcessPanelWorker$ProcessingJob.run(Unknown Source)
	at com.izforge.izpack.installer.ProcessPanelWorker.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
Apr 14, 2020 8:41:50 PM java.io.ObjectInputStream filterCheck
INFO: ObjectInputFilter REJECTED: class com.sun.crypto.provider.SealedObjectForKeyProtector, array length: -1, nRefs: 1, depth: 1, bytes: 70, ex: n/a
java.io.IOException: Invalid secret key format
	at com.ibm.crypto.provider.JceKeyStore.engineLoad(Unknown Source)

```
I have even tried to add unrestricted JCE jar files in my jre > security folder

**Comment by andreyzher** [comment]
Are you running on MacOSX with an IBM JDK by any chance?
IBM JDK uses IBM cryptography providers, but identifies itself with Oracle as the vendor which confuses the SPM infrastructure as Mac isn't an officially supported platform for SPM development, so this is not a combination we have verified.

The process of building SPM with Liberty either has to be done on Linux/Windows, or using an Oracle JDK on Mac.

**Comment by mikyjpeg** [comment]
Since there is no recent update to the ticket I'm going to close it. Feel free to reopen.
