### ISSUE TITLE
helm install spm fails on DB connection

### ISSUE THREAD

**Issue by parmarpIBM** [IBM/spm-kubernetes#38]
When I execute the helm install command to deploy SPM, the first job fails on connecting to DB2.  See log below.  

From my terminal, I can connect to DB2 successfully.  A google search suggests that DB2 be configured to enable tcpip for the DB2COMM config parameter, which is already set.  From my local SPM installation, a build configtest also connects to the DB.  

Any suggestions?

`Unable to locate tools.jar. Expected to find it in /opt/ibm/java/lib/tools.jar
Buildfile: /opt/ibm/Curam/release/CuramSDEJ/util/loadsql.xml

check.parameter.type:

check.db.type:

check.props.inside.file:

check.curam.environment.bindings.location.isset:

check.curam.environment.bindings.location.valid:

run.database.db2:

ora.use.servicename:

run.database.ora:

run.database.zos:

get.decrypted.db.password:

load:

targetDirectory:

BUILD FAILED
/opt/ibm/Curam/release/CuramSDEJ/util/loadsql.xml:40: The following error occurred while executing this line:
/opt/ibm/Curam/release/CuramSDEJ/util/loadsql.xml:53: com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2043][11550][4.21.29] Exception java.net.ConnectException: Error opening socket to server localhost/127.0.0.1 on port 50,000 with message: Connection refused (Connection refused). ERRORCODE=-4499, SQLSTATE=08001
	at com.ibm.db2.jcc.am.kd.a(kd.java:338)
	at com.ibm.db2.jcc.am.kd.a(kd.java:435)
	at com.ibm.db2.jcc.t4.ac.a(ac.java:440)
	at com.ibm.db2.jcc.t4.ac.<init>(ac.java:96)
	at com.ibm.db2.jcc.t4.a.b(a.java:366)
	at com.ibm.db2.jcc.t4.b.newAgent_(b.java:2076)
	at com.ibm.db2.jcc.am.Connection.initConnection(Connection.java:812)
	at com.ibm.db2.jcc.am.Connection.<init>(Connection.java:754)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:339)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:233)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:199)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:482)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:116)
	at org.apache.tools.ant.taskdefs.JDBCTask.getConnection(JDBCTask.java:364)
	at org.apache.tools.ant.taskdefs.SQLExec.getConnection(SQLExec.java:953)
	at org.apache.tools.ant.taskdefs.SQLExec.execute(SQLExec.java:649)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:380)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.net.Socket.connect(Socket.java:682)
	at com.ibm.db2.jcc.t4.w.run(w.java:49)
	at java.security.AccessController.doPrivileged(AccessController.java:734)
	at com.ibm.db2.jcc.t4.ac.a(ac.java:426)
	... 42 more

Total time: 16 seconds`

**Comment by andreyzher** [comment]
Hi @parmarpIBM 

`localhost` is not a valid hostname for the `global.database.hostname` property - it must be something that can be resolved from inside your Minikube cluster.

Try using the IP address of your development VM - this can that of your primary network interface, or that of the `docker0` interface, which should be `172.17.0.1`.

**Comment by parmarpIBM** [comment]
Thanks.  Using the IP address of the development VM worked for me.
